import User from "../../../images/avatar/b-sm.jpg";
import User2 from "../../../images/avatar/c-sm.jpg";
import User3 from "../../../images/avatar/a-sm.jpg";
import User4 from "../../../images/avatar/d-sm.jpg";

export const userData = [
  {
    id: 1,
    avatarBg: "purple",
    name: "Abu Bin Ishtiyak",
    displayName: "Ishtiak",
    dob: "10 Aug, 1980",
    role: "Customer",
    checked: false,
    email: "info@softnio.com",
    balance: "35040.34",
    phone: "818474958",
    emailStatus: "success",
    kycStatus: "success",
    lastLogin: "10 Feb 2020",
    status: "Active",
    address: "2337 Kildeer Drive",
    state: "Kentucky",
    country: "Canada",
    designation: "UI/UX Designer",
    projects: "213",
    performed: "87.5",
    tasks: "587",
  },
  {
    company: "XYZ Corp",
    registrationnumber: "54321",
    vta: "VTA543",
    address: "456 Elm St",
    zipcode: "54321",
    city: "Townsville",
    country: "Countryland",
    firstname: "Jane",
    lastname: "Smith",
    jobposition: "CTO",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Example Ltd",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "789 Oak St",
    zipcode: "98765",
    city: "Villagetown",
    country: "Countryland",
    firstname: "Michael",
    lastname: "Johnson",
    jobposition: "COO",
    email: "michael.johnson@example.com",
    phone: "555-123-4567",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Test Co",
    registrationnumber: "24680",
    vta: "VTA246",
    address: "135 Pine St",
    zipcode: "24680",
    city: "Woodville",
    country: "Countryland",
    firstname: "Emily",
    lastname: "Williams",
    jobposition: "Manager",
    email: "emily.williams@example.com",
    phone: "222-333-4444",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "Acme Corp",
    registrationnumber: "13579",
    vta: "VTA135",
    address: "246 Oak St",
    zipcode: "13579",
    city: "Treetown",
    country: "Countryland",
    firstname: "David",
    lastname: "Brown",
    jobposition: "Developer",
    email: "david.brown@example.com",
    phone: "777-888-9999",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Tech Solutions",
    registrationnumber: "56789",
    vta: "VTA567",
    address: "789 Maple St",
    zipcode: "56789",
    city: "Techville",
    country: "Countryland",
    firstname: "Sarah",
    lastname: "Miller",
    jobposition: "Designer",
    email: "sarah.miller@example.com",
    phone: "444-555-6666",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Innovate Inc",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "567 Birch St",
    zipcode: "98765",
    city: "Innovatown",
    country: "Countryland",
    firstname: "Kevin",
    lastname: "Jones",
    jobposition: "Engineer",
    email: "kevin.jones@example.com",
    phone: "111-222-3333",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "Global Services",
    registrationnumber: "23456",
    vta: "VTA234",
    address: "678 Cedar St",
    zipcode: "23456",
    city: "Globalville",
    country: "Countryland",
    firstname: "Jessica",
    lastname: "Davis",
    jobposition: "Analyst",
    email: "jessica.davis@example.com",
    phone: "666-777-8888",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Creative Designs",
    registrationnumber: "87654",
    vta: "VTA876",
    address: "789 Pine St",
    zipcode: "87654",
    city: "Creativetown",
    country: "Countryland",
    firstname: "Christopher",
    lastname: "Wilson",
    jobposition: "Artist",
    email: "christopher.wilson@example.com",
    phone: "999-888-7777",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Innovative Tech",
    registrationnumber: "54321",
    vta: "VTA543",
    address: "890 Oak St",
    zipcode: "54321",
    city: "Innovativetown",
    country: "Countryland",
    firstname: "Laura",
    lastname: "Taylor",
    jobposition: "Manager",
    email: "laura.taylor@example.com",
    phone: "777-666-5555",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "Sunrise Industries",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "123 Elm St",
    zipcode: "98765",
    city: "Sunrisetown",
    country: "Countryland",
    firstname: "Matthew",
    lastname: "Anderson",
    jobposition: "Director",
    email: "matthew.anderson@example.com",
    phone: "888-999-0000",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Swift Logistics",
    registrationnumber: "13579",
    vta: "VTA135",
    address: "456 Maple St",
    zipcode: "13579",
    city: "Swiftville",
    country: "Countryland",
    firstname: "Amanda",
    lastname: "Harris",
    jobposition: "Coordinator",
    email: "amanda.harris@example.com",
    phone: "555-444-3333",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Data Systems",
    registrationnumber: "56789",
    vta: "VTA567",
    address: "789 Oak St",
    zipcode: "56789",
    city: "Datatown",
    country: "Countryland",
    firstname: "Daniel",
    lastname: "Martin",
    jobposition: "Analyst",
    email: "daniel.martin@example.com",
    phone: "444-333-2222",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "EcoTech",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "234 Elm St",
    zipcode: "98765",
    city: "Ecoville",
    country: "Countryland",
    firstname: "Olivia",
    lastname: "Clark",
    jobposition: "Engineer",
    email: "olivia.clark@example.com",
    phone: "111-222-3333",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Innovative Solutions",
    registrationnumber: "23456",
    vta: "VTA234",
    address: "456 Cedar St",
    zipcode: "23456",
    city: "Innovativetown",
    country: "Countryland",
    firstname: "William",
    lastname: "Young",
    jobposition: "Developer",
    email: "william.young@example.com",
    phone: "666-777-8888",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "GlobeTech",
    registrationnumber: "87654",
    vta: "VTA876",
    address: "678 Pine St",
    zipcode: "87654",
    city: "Globetown",
    country: "Countryland",
    firstname: "Sophia",
    lastname: "Lee",
    jobposition: "Manager",
    email: "sophia.lee@example.com",
    phone: "999-888-7777",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "Rainbow Co",
    registrationnumber: "54321",
    vta: "VTA543",
    address: "890 Elm St",
    zipcode: "54321",
    city: "Rainbowtown",
    country: "Countryland",
    firstname: "Jackson",
    lastname: "Garcia",
    jobposition: "Designer",
    email: "jackson.garcia@example.com",
    phone: "777-666-5555",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Golden Harvest",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "123 Cedar St",
    zipcode: "98765",
    city: "Goldentown",
    country: "Countryland",
    firstname: "Mia",
    lastname: "Lopez",
    jobposition: "Director",
    email: "mia.lopez@example.com",
    phone: "888-999-0000",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Swift Solutions",
    registrationnumber: "13579",
    vta: "VTA135",
    address: "456 Oak St",
    zipcode: "13579",
    city: "Swiftville",
    country: "Countryland",
    firstname: "Liam",
    lastname: "Rivera",
    jobposition: "Coordinator",
    email: "liam.rivera@example.com",
    phone: "555-444-3333",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "TechMasters",
    registrationnumber: "56789",
    vta: "VTA567",
    address: "789 Elm St",
    zipcode: "56789",
    city: "Techville",
    country: "Countryland",
    firstname: "Emma",
    lastname: "Stewart",
    jobposition: "Analyst",
    email: "emma.stewart@example.com",
    phone: "444-333-2222",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Nature's Best",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "234 Cedar St",
    zipcode: "98765",
    city: "Naturetown",
    country: "Countryland",
    firstname: "Noah",
    lastname: "Mitchell",
    jobposition: "Engineer",
    email: "noah.mitchell@example.com",
    phone: "111-222-3333",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "Innovative Creations",
    registrationnumber: "23456",
    vta: "VTA234",
    address: "456 Pine St",
    zipcode: "23456",
    city: "Innovativetown",
    country: "Countryland",
    firstname: "Ava",
    lastname: "Perez",
    jobposition: "Developer",
    email: "ava.perez@example.com",
    phone: "666-777-8888",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "FutureTech",
    registrationnumber: "87654",
    vta: "VTA876",
    address: "678 Elm St",
    zipcode: "87654",
    city: "Futureville",
    country: "Countryland",
    firstname: "Jackson",
    lastname: "Sanchez",
    jobposition: "Manager",
    email: "jackson.sanchez@example.com",
    phone: "999-888-7777",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Skyline Innovations",
    registrationnumber: "54321",
    vta: "VTA543",
    address: "890 Cedar St",
    zipcode: "54321",
    city: "Skylinetown",
    country: "Countryland",
    firstname: "Sophia",
    lastname: "Ramirez",
    jobposition: "Designer",
    email: "sophia.ramirez@example.com",
    phone: "777-666-5555",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "TechGenius",
    registrationnumber: "98765",
    vta: "VTA987",
    address: "123 Pine St",
    zipcode: "98765",
    city: "Techville",
    country: "Countryland",
    firstname: "Liam",
    lastname: "Ward",
    jobposition: "Director",
    email: "liam.ward@example.com",
    phone: "888-999-0000",
    createdDate: "2023-08-13",
    status: "Active",
  },
  {
    company: "EcoSolutions",
    registrationnumber: "13579",
    vta: "VTA135",
    address: "456 Cedar St",
    zipcode: "13579",
    city: "Ecotown",
    country: "Countryland",
    firstname: "Emma",
    lastname: "Turner",
    jobposition: "Coordinator",
    email: "emma.turner@example.com",
    phone: "555-444-3333",
    createdDate: "2023-08-13",
    status: "Pending",
  },
  {
    company: "Innovative Systems",
    registrationnumber: "56789",
    vta: "VTA567",
    address: "789 Pine St",
    zipcode: "56789",
    city: "Innovativetown",
    country: "Countryland",
    firstname: "Noah",
    lastname: "Gonzalez",
    jobposition: "Analyst",
    email: "noah.gonzalez@example.com",
    phone: "444-333-2222",
    createdDate: "2023-08-13",
    status: "Suspended",
  },
  {
    company: "TechWizards",
    registrationnumber: "87654",
    vta: "VTA876",
    address: "678 Cedar St",
    zipcode: "87654",
    city: "Techville",
    country: "Countryland",
    firstname: "Olivia",
    lastname: "Hill",
    jobposition: "Engineer",
    email: "olivia.hill@example.com",
    phone: "999-888-7777",
    createdDate: "2023-08-13",
    status: "Active",
  },
];

export const notes = [
  {
    id: 1,
    text: "Aproin at metus et dolor tincidunt feugiat eu id quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean sollicitudin non nunc vel pharetra.",
    date: "November 18, 2019",
    time: "5:34 pm",
    company: "Softnio",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend libero semper metus aliquam tempus. Sed efficitur elit et ligula lobortis",
    date: "December 27, 2019",
    time: "7:00 pm",
    company: "Softnio",
  },
];

export const filterStatus = [
  { value: "Active", label: "Active" },
  { value: "Pending", label: "Pending" },
  { value: "Suspend", label: "Suspend" },
];

export const filterRole = [
  { value: "investor", label: "Investor" },
  { value: "seller", label: "Seller" },
  { value: "buyer", label: "Buyer" },
];

export const countryOptions = [
  { value: "Canada", label: "Canada" },
  { value: "USA", label: "USA" },
  { value: "India", label: "India" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "France", label: "France" },
  { value: "England", label: "England" },
];
